$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$BackendEnvPath = Join-Path $ProjectRoot "backend\.env"
$FrontendEnvLocalPath = Join-Path $ProjectRoot "frontend\.env.local"

function Read-DotEnv($Path) {
    $values = @{}
    if (-not (Test-Path $Path)) {
        return $values
    }

    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $idx = $line.IndexOf("=")
        if ($idx -le 0) { return }

        $key = $line.Substring(0, $idx).Trim()
        $value = $line.Substring($idx + 1).Trim()
        $value = $value.Trim('"').Trim("'")
        $values[$key] = $value
    }

    return $values
}

$backendEnv = Read-DotEnv $BackendEnvPath
$frontendEnv = Read-DotEnv $FrontendEnvLocalPath

$supabaseUrl = $frontendEnv["VITE_SUPABASE_URL"]
if (-not $supabaseUrl) { $supabaseUrl = $backendEnv["SUPABASE_URL"] }

$supabaseAnonKey = $frontendEnv["VITE_SUPABASE_ANON_KEY"]
if (-not $supabaseAnonKey) { $supabaseAnonKey = $backendEnv["SUPABASE_ANON_KEY"] }
if (-not $supabaseAnonKey) {
    $supabaseAnonKey = $backendEnv["SUPABASE_KEY"]
    if ($supabaseAnonKey) {
        Write-Host "Using backend SUPABASE_KEY as frontend anon key. Make sure it is NOT a service-role key." -ForegroundColor Yellow
    }
}

if (-not $supabaseUrl) {
    Write-Host "Missing Supabase URL. Add SUPABASE_URL to backend\.env or VITE_SUPABASE_URL to frontend\.env.local" -ForegroundColor Red
}

if (-not $supabaseAnonKey) {
    Write-Host "Missing Supabase anon key. Add SUPABASE_ANON_KEY to backend\.env or VITE_SUPABASE_ANON_KEY to frontend\.env.local" -ForegroundColor Red
}

if ($supabaseUrl -and $supabaseAnonKey) {
    $content = @"
# Generated by sync-frontend-env.ps1
# Vite exposes only variables prefixed with VITE_ to browser code.
VITE_SUPABASE_URL=$supabaseUrl
VITE_SUPABASE_ANON_KEY=$supabaseAnonKey
"@
    Set-Content -Path $FrontendEnvLocalPath -Value $content -Encoding UTF8
    Write-Host "Updated frontend\.env.local for Vite." -ForegroundColor Green
}
