# FoodVault static thumbnail library — keyword list (~140)
# Each entry: keyword (matched against recipe titles, lowercase) -> short scene hint for generation

KEYWORDS = {
    # ── Indian mains ──
    "biryani": "fragrant chicken biryani in a handi pot with saffron rice",
    "dosa": "crispy golden dosa with sambar and chutneys",
    "idli": "soft white idlis with sambar and coconut chutney",
    "vada": "crispy medu vada with chutney",
    "samosa": "golden fried samosas with mint chutney",
    "pakora": "crispy vegetable pakoras in a basket",
    "paratha": "flaky layered paratha with butter",
    "roti": "soft chapati rotis stacked",
    "naan": "charred garlic naan bread",
    "curry": "rich curry in a bowl with garnish",
    "dal": "yellow dal tadka in a brass bowl",
    "paneer": "paneer butter masala in creamy tomato gravy",
    "chole": "chana masala chickpea curry",
    "rajma": "rajma kidney bean curry with rice",
    "tikka": "chicken tikka skewers charred",
    "tandoori": "tandoori chicken on a sizzling plate",
    "korma": "creamy vegetable korma",
    "vindaloo": "spicy pork vindaloo curry",
    "khichdi": "comforting moong dal khichdi",
    "poha": "flattened rice poha with peanuts and curry leaves",
    "upma": "semolina upma with vegetables",
    "pulao": "vegetable pulao rice",
    "sambar": "south indian sambar stew",
    "rasam": "peppery rasam soup",
    "kofta": "malai kofta in creamy gravy",
    "bhaji": "pav bhaji with buttered buns",
    "dhokla": "steamed yellow dhokla squares",
    "uttapam": "onion tomato uttapam",
    "halwa": "carrot halwa garnished with nuts",
    "ladoo": "golden besan ladoos",
    "barfi": "milk barfi squares with pistachio",
    "kheer": "rice kheer in a clay bowl",
    "jalebi": "orange spiral jalebis",
    "gulab jamun": "gulab jamuns in syrup",
    "chaat": "colorful papdi chaat with yogurt and chutneys",
    "pani puri": "pani puri golgappa with flavored water",
    "vada pav": "vada pav with green chutney",
    "momos": "steamed momos with red chutney",
    # ── Rice & grains ──
    "fried rice": "vegetable fried rice in a wok",
    "rice bowl": "rice bowl with toppings",
    "risotto": "creamy mushroom risotto",
    "quinoa": "quinoa salad bowl with vegetables",
    "oats": "creamy bowl of oatmeal with berries",
    "porridge": "warm porridge with honey drizzle",
    "granola": "granola bowl with yogurt and fruit",
    # ── Pasta & Italian ──
    "pasta": "spaghetti in tomato sauce with basil",
    "spaghetti": "spaghetti with marinara and parmesan",
    "lasagna": "cheesy lasagna slice with layers visible",
    "mac and cheese": "creamy mac and cheese",
    "penne": "penne arrabbiata",
    "alfredo": "fettuccine alfredo creamy pasta",
    "carbonara": "spaghetti carbonara with pancetta",
    "gnocchi": "pan-seared gnocchi with sage butter",
    "pizza": "wood-fired margherita pizza",
    "garlic bread": "cheesy garlic bread slices",
    "bruschetta": "tomato basil bruschetta",
    # ── Asian ──
    "noodles": "stir-fried noodles with vegetables in a wok",
    "ramen": "steaming ramen bowl with egg and chashu",
    "pho": "vietnamese pho with herbs",
    "pad thai": "pad thai with lime and peanuts",
    "sushi": "assorted sushi rolls on a slate plate",
    "dumplings": "steamed dumplings in a bamboo basket",
    "spring roll": "crispy spring rolls with dipping sauce",
    "stir fry": "colorful vegetable stir fry in a wok",
    "teriyaki": "chicken teriyaki glazed with sesame",
    "katsu": "chicken katsu with rice",
    # ── Western mains ──
    "burger": "juicy burger with melted cheese and lettuce",
    "sandwich": "stacked club sandwich cut diagonally",
    "wrap": "grilled wrap halves with filling visible",
    "taco": "three street tacos with cilantro and lime",
    "burrito": "burrito cut in half showing filling",
    "quesadilla": "cheesy quesadilla wedges with salsa",
    "nachos": "loaded nachos with cheese and jalapenos",
    "steak": "seared steak sliced with herb butter",
    "grilled chicken": "grilled chicken breast with herbs",
    "roast chicken": "whole roast chicken golden brown",
    "chicken wings": "glazed chicken wings with sesame",
    "fried chicken": "crispy fried chicken pieces",
    "nuggets": "golden chicken nuggets with dip",
    "kebab": "grilled kebab skewers with vegetables",
    "meatball": "meatballs in tomato sauce",
    "fish": "pan-seared fish fillet with lemon",
    "salmon": "grilled salmon with asparagus",
    "shrimp": "garlic butter shrimp in a skillet",
    "prawn": "grilled prawns with lime",
    "fish and chips": "fish and chips with tartar sauce",
    "bbq": "barbecue ribs glazed",
    "pork": "roast pork slices with gravy",
    "lamb": "lamb chops with rosemary",
    "meatloaf": "meatloaf slices with glaze",
    "casserole": "bubbling baked casserole dish",
    "pot pie": "golden chicken pot pie",
    "mashed potato": "creamy mashed potatoes with butter pool",
    "potato": "crispy roasted potato bites with herbs",
    "fries": "golden french fries in a paper cone",
    "hash brown": "crispy hash browns",
    # ── Breakfast ──
    "pancake": "stack of pancakes with maple syrup",
    "waffle": "waffles with berries and cream",
    "french toast": "french toast with powdered sugar and berries",
    "omelette": "fluffy folded omelette with herbs",
    "scrambled egg": "creamy scrambled eggs on toast",
    "boiled egg": "soft boiled eggs on avocado toast",
    "egg": "sunny side up eggs in a skillet",
    "toast": "avocado toast with chili flakes",
    "bagel": "bagel with cream cheese and salmon",
    "croissant": "buttery flaky croissants",
    "muffin": "blueberry muffins on a cooling rack",
    "cereal": "cereal bowl with milk and fruit",
    # ── Soups & salads ──
    "soup": "creamy soup bowl with swirl of cream and herbs",
    "tomato soup": "roasted tomato soup with basil",
    "chicken soup": "chicken noodle soup",
    "broth": "clear vegetable broth with herbs",
    "stew": "hearty beef stew in a rustic bowl",
    "chili": "bowl of chili con carne with toppings",
    "salad": "fresh garden salad with vinaigrette",
    "caesar salad": "caesar salad with parmesan shavings",
    "fruit salad": "colorful fruit salad bowl",
    "coleslaw": "creamy coleslaw",
    "hummus": "hummus plate with olive oil and paprika",
    "guacamole": "guacamole with tortilla chips",
    # ── Snacks ──
    "popcorn": "buttered popcorn in a striped box",
    "chips": "homemade potato chips",
    "cutlet": "crispy vegetable cutlets",
    "roll": "stuffed roll wraps cut showing filling",
    "puff": "golden puff pastry snacks",
    "fritter": "crispy fritters with dip",
    "tikki": "aloo tikki patties with chutney",
    "spring onion": "savory scallion pancakes",
    # ── Sweets & baking ──
    "cake": "frosted layer cake slice",
    "chocolate cake": "rich chocolate cake with ganache",
    "cheesecake": "creamy cheesecake slice with berry sauce",
    "cupcake": "frosted cupcakes with sprinkles",
    "brownie": "fudgy brownie stack",
    "cookie": "chocolate chip cookies on a rack",
    "donut": "glazed donuts with sprinkles",
    "pie": "lattice-top fruit pie",
    "apple pie": "apple pie slice with ice cream",
    "tart": "fruit tart with glaze",
    "pudding": "chocolate pudding with cream",
    "ice cream": "ice cream scoops in a bowl with toppings",
    "mousse": "chocolate mousse in a glass",
    "crepe": "folded crepes with strawberries",
    "banana bread": "sliced banana bread loaf",
    "bread": "rustic sourdough bread loaf sliced",
    # ── Drinks ──
    "smoothie": "berry smoothie in a glass with fruit garnish",
    "smoothie bowl": "smoothie bowl topped with granola and fruit",
    "shake": "milkshake with whipped cream and straw",
    "milkshake": "chocolate milkshake with whipped cream",
    "juice": "fresh orange juice with fruit",
    "lassi": "mango lassi in a clay cup",
    "lemonade": "iced lemonade with mint",
    "coffee": "latte with latte art",
    "tea": "masala chai in a glass with spices",
    "hot chocolate": "hot chocolate with marshmallows",
    # ── Generic category fallbacks ──
    "_fallback_snacks": "assorted appetizing snack platter",
    "_fallback_rice": "steamed rice bowl with garnish",
    "_fallback_salads": "fresh mixed salad bowl",
    "_fallback_shakes": "milkshake glass with garnish",
    "_fallback_smoothie": "fruit smoothie glasses",
    "_fallback_dessert": "assorted dessert platter",
    "_fallback_breakfast": "breakfast spread with eggs and toast",
    "_fallback_dinner": "home-cooked dinner plate",
    "_fallback_generic": "beautifully plated home-cooked meal",
}

STYLE = (
    "Professional food photography, overhead 45-degree angle, warm natural light, "
    "cream linen background, rustic ceramic plate, shallow depth of field, "
    "appetizing, vibrant, no text, no people, no hands"
)
